mit-ll-responsible-ai/hydra-zen

- setup.py
1.1.0 was officially released 5 days ago: https://github.com/facebookresearch/hydra/releases/tag/v1.1.0
> bump hydra-core dep to v1.1.0

- src/hydra_zen/structured_configs/_implementations.py
- tests/test_signature_parsing.py
> builds skips unresolved forward references

- README.md
> Adds Zenodo DOI badge for citations

- .pre-commit-config.yaml
- src/hydra_zen/structured_configs/_implementations.py
- tests/annotations/declarations.py
- tests/test_utils.py
> Update mutable_value annotation to enable clean usage with dataclass def

- src/hydra_zen/structured_configs/_implementations.py
- tests/test_hydra_behaviors.py
- tests/test_validation.py
> hydra_partial=True no longer requires hydra_recursive=True

- docs/source/how_to/pytorch_lightning.rst
> PL How-To revision

- src/hydra_zen/structured_configs/_implementations.py
- tests/test_meta_fields.py
Closes #161 
- First commit should fail - indicating that our tests now catch this.
- Second commit should fix the bug
> Fixes meta-field + pop-sig bug reported in #161

- docs/source/tutorials/config_groups.rst
- src/hydra_zen/structured_configs/_implementations.py
> Touchup docs

- .github/workflows/nightly.yml
- docs/source/api_reference.rst
- docs/source/changes.rst
- tests/test_value_conversion.py
Also have pyright scan `scr/` during nightly job.
> Update changelog and ref docs for v0.4.0

- .github/workflows/nightly.yml
- .github/workflows/tox_run.yml
See for upstream bug report that explains our failing CI https://github.com/microsoft/pyright/issues/2746
> pin pyright to 1.1.197 until bugfix in pyright comes through

- tests/test_value_conversion.py
Fix flaky test that was filtering all non-numeric strings, which should have been filtering only numeric strings.
> Fix flaky test

- docs/source/changes.rst
- src/hydra_zen/structured_configs/_implementations.py
- tests/test_make_config.py
> Ensure Builds-annotations are preserved by make_config

- tests/test_value_conversion.py
`functools.partial` automatically flattens itself:
`partial(partial(dict, a=1) b=2)` -> `partial(dict, a=1, b=2)`
Thus `builds` handles arbitrarily-nested partial'd targets "for free". This test ensures that my assumptions here are correct, and that this behavior is consistent across Python versions.
> Add test ensuring nested functools.partial is supported

- .github/workflows/nightly.yml
- .github/workflows/tox_run.yml
Tracking here: https://github.com/microsoft/pyright/issues/2902
> pin pyright to 1.1.211 until upstream bug is fixed

- src/hydra_zen/structured_configs/_implementations.py
- tests/test_signature_parsing.py
> Apply type-widening when field configured with interpolated string

- .github/workflows/nightly.yml
- .github/workflows/tox_run.yml
Tracking bug in pyright 1.1.215 here: https://github.com/microsoft/pyright/issues/2938
> pin pyright 1.1.214

- .github/workflows/nightly.yml
- .github/workflows/tox_run.yml
- src/hydra_zen/typing/_implementations.py
Tracking up stream pyright bug at https://github.com/microsoft/pyright/issues/2998
> Pin pyright to 1.1.217

- docs/requirements.txt
- docs/source/tutorials/add_cli.rst
- docs/source/tutorials/basic_app.rst
- docs/source/tutorials/config_groups.rst
- docs/source/tutorials/hierarchy.rst
- docs/source/tutorials/inject_wrapper.rst
> Document help option

- src/hydra_zen/_utils/coerce.py
> Remove unnecessary type: ignore comment

- .github/workflows/nightly.yml
- .github/workflows/tox_run.yml
- setup.cfg
- setup.py
- src/hydra_zen/typing/_implementations.py
- tests/annotations/declarations.py
Pin pyright until https://github.com/microsoft/pyright/issues/3255 is resolves
> Update partial stub

- docs/source/changes.rst
- src/hydra_zen/structured_configs/_utils.py
- tests/test_signature_parsing.py
> Fix `builds(<class_method>)` derived via inheritance

- src/hydra_zen/structured_configs/_utils.py
> fix signature inconsistencies in _utils

- docs/source/how_to/pytorch_lightning.rst
- docs/source/tutorials/add_cli.rst
- docs/source/tutorials/basic_app.rst
- docs/source/tutorials/config_groups.rst
- docs/source/tutorials/hierarchy.rst
- docs/source/tutorials/inject_wrapper.rst
- src/hydra_zen/_launch.py
> Broaden annotation for launch and fix docs

- .github/workflows/nightly.yml
- .github/workflows/tox_run.yml
pin mypy until https://github.com/python/mypy/issues/14031 is resolved
> pin mypy until recursive types are fixed

- pyproject.toml
- src/hydra_zen/structured_configs/_implementations.py
- src/hydra_zen/structured_configs/_make_config.py
- src/hydra_zen/structured_configs/_make_custom_builds.py
- src/hydra_zen/typing/_implementations.py
- src/hydra_zen/wrapper/_implementations.py
- tests/pyright_utils.py
- tests/test_docstrings.py
Our coverage job now runs this. 
Also fixes docstring errors caught by pyright.
> Scan docstring examples with pyright

- .github/workflows/tox_run.yml
- docs/source/changes.rst
- pyproject.toml
- src/hydra_zen/typing/_implementations.py
- tests/test_protocols.py
- tests/test_py39.py
- tests/test_third_party/test_using_beartype.py
> Fix Partial.__class_getitem__

- .github/workflows/tox_run.yml
- docs/source/changes.rst
- pyproject.toml
- src/hydra_zen/_compatibility.py
- src/hydra_zen/structured_configs/_implementations.py
- src/hydra_zen/structured_configs/_just.py
- src/hydra_zen/structured_configs/_make_config.py
- src/hydra_zen/structured_configs/_make_custom_builds.py
- src/hydra_zen/structured_configs/_utils.py
- tests/custom_strategies.py
- tests/test_hydra_behaviors.py
> Closes #336 -- hydra_convert='object' is supported

- .github/workflows/tox_run.yml
- README.md
- docs/source/changes.rst
- pyproject.toml
- src/hydra_zen/structured_configs/_implementations.py
- src/hydra_zen/structured_configs/_make_config.py
- tests/custom_strategies.py
- tests/test_config_value_validation.py
- tests/test_dataclass_conversion.py
- tests/test_py310.py
- tests/test_value_conversion.py
> Adds support for python 3.11

- .github/workflows/tox_run.yml
- docs/source/how_to/pytorch_lightning.rst
- pyproject.toml
- src/hydra_zen/wrapper/_implementations.py
- tests/pyright_utils.py
> test that docs build in CI; update some docstrings; update pyright scan utils

- src/hydra_zen/wrapper/_implementations.py
- tests/example_app/change_hydra_config.py
- tests/test_signature_parsing.py
- tests/test_store.py
> Infer name/group for storing HydraConf instances/subclasses

- .pre-commit-config.yaml
- src/hydra_zen/_hydra_overloads.py
- src/hydra_zen/_launch.py
- src/hydra_zen/_utils/coerce.py
- src/hydra_zen/structured_configs/_implementations.py
- src/hydra_zen/structured_configs/_utils.py
- src/hydra_zen/typing/_builds_overloads.py
- tests/annotations/declarations.py
- tests/custom_strategies.py
- tests/pyright_utils.py
- tests/test_compatibility/test_hydra_supports_partial.py
- tests/test_compatibility/test_omegaconf_830.py
- tests/test_compatibility/test_primitive_support.py
- tests/test_config_value_validation.py
- tests/test_dataclass_semantics.py
- tests/test_hydra_behaviors.py
- tests/test_make_config.py
- tests/test_signature_parsing.py
- tests/test_third_party/test_type_validators.py
- tests/test_third_party/test_using_pydantic.py
- tests/test_utils.py
- tests/test_validation.py
- tests/test_zen.py
- tests/test_zen_processing/test_inheritance.py
- tests/test_zen_processing/test_zen_wrappers.py
- Upgrades `black` to [stable style 2023](https://black.readthedocs.io/en/stable/change_log.html#id3)
- Fixes a flaky hypothesis test that could draw `'???'`, which Hydra treats as `MISSING` and thus fails our test
> Fix failing CI

- docs/requirements.txt
- docs/source/changes.rst
- docs/source/conf.py
- docs/source/generated/hydra_zen.ZenStore.rst
- docs/source/generated/hydra_zen.zen.rst
- docs/source/how_to/using_scikit_learn.rst
- docs/source/index.rst
- src/hydra_zen/wrapper/_implementations.py
- tests/pyright_utils.py
- tests/test_docs_typecheck.py
- Add "hydra-zen at a glance" section to landing page
- Improve ZenStore docs
- Fix deprecated favicon spec
> Doc improvements

- docs/source/changes.rst
- src/hydra_zen/wrapper/_implementations.py
- tests/test_zen.py
> make config resolution configurable in zen

- docs/source/how_to/pytorch_lightning.rst
- docs/source/index.rst
- docs/source/tutorials/add_cli.rst
- docs/source/tutorials/basic_app.rst
- tests/test_store.py
> add annotations to intro docs and link hydra-store in at-a-glance

- tests/test_third_party/test_using_beartype.py
see https://github.com/beartype/beartype/issues/241
> Remove failing test due to upstream bug 

- pyproject.toml
No time to dig into fixing compat issues at this point
> Pin pydantic < 2.0

- tests/conftest.py
No more deprecation messages :)
> pkg_resources -> importlib.metadata

- src/hydra_zen/structured_configs/_implementations.py
- tests/test_BuildsFn.py
> Ensure zen conversion functions leverage 3rd party BuildsFn

- docs/source/index.rst
Hi @rsokl, I hope you're doing well!
This PR fixes a minor grammatical error in the docs.
> Typo in index.rst

- README.md
> docs: add conda version badge and link to readme

- pyproject.toml
https://github.com/HypothesisWorks/hypothesis/issues/4144
Closes #740
> Pin hypothesis to avoid buggy everything_except

- src/hydra_zen/wrapper/_implementations.py
> Refactor _StoreCallSig to inline form (2)
