src/hydra_zen/_hydra_overloads.py
src/hydra_zen/typing.py
tests/annotations/behaviors.py
tests/annotations/declarations.py

We don't know ahead of time what it should or shouldn't accept, since we don't have access to its true signature.
Before:
After:
Before:
After:

Fix typing behavior

---

.github/workflows/nightly.yml
src/hydra_zen/_hydra_overloads.py

`Callable[..., T]` has to be prioritized over `Type[T]` in the overloads
Add pyright run to nightly

typing: change overload priorities for instantiate (pyright compat)

---

src/hydra_zen/structured_configs/_implementations.py
tests/test_protocols.py
tests/test_signature_parsing.py

Hydra's type-checking occurs prior to recursive instantiation. This means that, e.g., passing a type-`Builds[int]` argument to a field `x: int` will trigger Hydra's type-checking upon recursive instantiation, even though the recursive instantiation will appropriately produce `int` for that argument.
To address this, hydra-zen now applies type auto-widening to accommodate a case where a user supplies a `Builds`-type argument to a non-`Any` field (addresses https://github.com/facebookresearch/hydra/issues/1759)
Given:
```python
def returns_int() -> int:
return 1
def expects_int(x: int) -> int:
returns x
```
Before:
```python
>>> instantiate(builds(expects_int, x=builds(returns_int))) 
---------------------------------------------------------------------------
ValidationError: Invalid type …
```

Applies type auto-widening to accommodate Builds-as-default

---

src/hydra_zen/experimental/_implementations.py
src/hydra_zen/typing/__init__.py
src/hydra_zen/typing/_implementations.py

Moved the implementations of our protocols to `hydra_zen.typing._implementations` so that the namespace of `hydra_zen.typing` consists only of the types that we choose to ship. 
The only compatibility-breaking change is that `hydra_zen.typing.DataClass` was made to be strictly internal, since I don't want to purport to be providing a satisfactory protocol for describing dataclasses in general.
I am on the fence of exposing `hydra_zen.typing.Partial`, for similar reasons to making `DataClass` internal, but it does seem useful to facilitate convenient annotations for our users like 
```python
def custom_instantiate(x: PartialBuilds[T]) -> Partial[T]:
...
```
Also, I am more confident that our `Partial` protocol is sufficiently general.

cleanup namespace for hydra_zen.typing

---

src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

Fixes the `DataClass` protocol, which was too narrow, and adds a pyright test.
Our `DataClass` included a spurious field that is not recognized by pyright. This did not prevent `Builds` et al. from being seen broadly as dataclasses, since our protocol was overly narrow rather than broad.

add pyright test for  dataclass protocol

---

docs/source/installation.rst
src/hydra_zen/_hydra_overloads.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/experimental/test_logging.py
tests/test_hydrated_dataclass.py
tests/test_roundtrips.py
tests/test_signature_parsing.py
tests/test_utils.py
tests/test_validation.py
tests/test_validation_py38.py

[shed](https://pypi.org/project/shed/)
> shed canonicalises Python code. Shed your legacy, stop bikeshedding, and move on. Black++
We are already black & isort compliant, so the main changes are removing unused imports

run shed auto-formatter on everything

---

setup.py

Closes #96 
After PR:
```shell
$ echo "from hydra_zen import builds" > tmp.py
$ mypy tmp.py
Success: no issues found in 1 source file
```

add py.typed for PEP 561 compliance

---

src/hydra_zen/__init__.py
src/hydra_zen/_hydra_overloads.py
src/hydra_zen/experimental/__init__.py
src/hydra_zen/structured_configs/__init__.py
src/hydra_zen/typing/__init__.py

This is an attempt to fix  [this failing pyright run](https://github.com/mit-ll-responsible-ai/hydra-zen/runs/3599564153).
This was flagged by a new diagnostic rule https://github.com/microsoft/pyright/releases/tag/1.1.168:
> Enhancement: Added reportPrivateImportUsage diagnostic rule, which reports usage of a symbol from a py.typed library that is not intended to be re-exported by the library's author. The rule is on by default in basic type checking mode but can be disabled. Completion provider no longer offers these symbols as completion suggestions.

Define __all__ fields in all public modules

---

docs/source/experimental.rst
docs/source/overview.rst
docs/source/structured_configs.rst
src/hydra_zen/structured_configs/_implementations.py

- Documents features that introduce explicit hydra-zen dependencies, as mentioned in https://github.com/mit-ll-responsible-ai/hydra-zen/pull/102#issuecomment-922265666. 
- Introduces `pycon`-style codeblocks where appropriate
- Improves consistency of monospace formatting in docstrings

Improving docs

---

src/hydra_zen/structured_configs/_implementations.py

This didn't actually cause any bugs - ultimately `return False` was still reached - but it *looked* like a bug.

Fix bare False in is_just

---

.github/workflows/tox_run.yml
setup.cfg
setup.py
tests/test_validation.py

The introduction of `TypeGuard` in #110  bumped our minimum dependency on typing-extensions, but our CI failed to catch it.
Also, we were testing `hydra-core==1.1.0dev7`, not `hydra-core==1.1.0`

bump min typing-extensions dependency; test all minimum dependencies

---

src/hydra_zen/structured_configs/_utils.py
tests/test_roundtrips.py
tests/test_third_party/test_against_numpy.py
tests/test_utils.py

closes #113
Before:
```python
>>> import random
>>> instantiate(builds(random.uniform, 2, 4))
TypeError: Error instantiating 'random.Random.uniform' : uniform() missing 1 required positional argument: 'b'
```
After:
```python
>>> instantiate(builds(random.uniform, 2, 4))
3.17287981209861248960842
```

Bug fix: get_obj_path no longer looks at __qualname__

---

src/hydra_zen/structured_configs/_implementations.py
tests/test_roundtrips.py

Before:
```python
>>> conf = builds(dict, a="${.hi}", hydra_meta=dict(hi=1))
>>> get_target(conf)
<function hydra_zen.funcs.zen_processing(*args, _zen_target: str, _zen_partial: bool = False, _zen_exclude: Sequence[str] = (), _zen_wrappers: Union[str, Sequence[str]] = (), **kwargs)>
```
After
```python
>>> conf = builds(dict, a="${.hi}", hydra_meta=dict(hi=1))
>>> get_target(conf)
dict
```

Bug fix: get_target with zen_processing

---

docs/source/how_to/beartype.rst
docs/source/how_to/pytorch_lightning.rst
docs/source/how_tos.rst
docs/source/tutorials/add_cli.rst
docs/source/tutorials/basic_app.rst
docs/source/tutorials/config_groups.rst
docs/source/tutorials/hierarchy.rst
docs/source/tutorials/inject_wrapper.rst

Main improvement: avoid
```python
cfg = instantiate(cfg)
```
pattern in docs. As pointed out by @jgbos and others, this is needlessly misleading!

Docs touchup

---

setup.py

The tarballs live at
```
https://github.com/mit-ll-responsible-ai/hydra-zen/tarball/vX.X.X
```
not
```
https://github.com/mit-ll-responsible-ai/hydra-zen/tarball/X.X.X
```

Fix project tarball URL

---

.github/workflows/tox_run.yml

Tracking here: https://github.com/microsoft/pyright/issues/2549

pin pyright to 1.1.184 in CI until 1.1.186 is released

---

docs/source/api_reference.rst
docs/source/changes.rst
src/hydra_zen/errors.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/structured_configs/_value_conversion.py
src/hydra_zen/typing/__init__.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/conftest.py
tests/test_config_value_validation.py
tests/test_dataclass_semantics.py
tests/test_third_party/test_type_validators.py
tests/test_value_conversion.py

> The Eyes of T.J. Eckleburg, *The Great Gatsby* (2013)
Closes #149 
Prior to this PR, hydra-zen would not check configured values to see if they are compatible with Hydra's supported primitives. This means that you could construct a config via `builds` and `make_config` that are destined to raise whenever Hydra tries to serialize or instantiate the config. This is no good!
**Before**:
```python
from hydra_zen import make_config, to_yaml, instantiate, builds
class MyCustomClass:
pass
```
```python
>>> not_supported = MyCustomClass()
>>> Conf = make_config(a=not_supported)  # hydra-zen is OK with this even though it is doomed to fail
>>> to_yaml(Conf)   # will raise
>>> instantiate(Conf) # will raise
```
Also, our annotations did not provide any feedback along these lines
**After**:
Now …

Add strict validation against Hydra's supported primitives

---

.pre-commit-config.yaml
setup.py
src/hydra_zen/structured_configs/_implementations.py
tests/conftest.py
tests/test_third_party/test_against_numpy.py

hydra-zen provides specialized support for numpy so that its functions/classes can seamlessly be configured by our tools. This involves some "magic" on our end. Previously, we imported numpy if it was installed in a user's env. Well, things just got more magical: we now provide the same automatic support for numpy, but hydra-zen will never be first to import numpy.
Why bother with this? Because hydra-zen's support for numpy is not an obvious characteristic of the library, and we don't want users to be sent on a wild goose chase, trying to figure out where in *their* code they are importing NumPy. In general, we want the footprint left behind by hydra-zen to be as minimal as possible.
Note to devs: you'll need to upgrade your installation of hypothesis to get this new test to pass

ENH: hydra-zen will never be the first to import numpy

---

setup.cfg
src/hydra_zen/errors.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
tests/test_hydra_behaviors.py
tests/test_make_config.py

Closes #170 
For users using `omegaconf` 2.1.1 or earlier, we provide a patch of an upstream bug.
Before:
```python
>>> A = make_config(x=1)
>>> B = make_config(x=[1, 2], bases=(A,))  # must be a mutable value to trigger the bug
>>> instantiate(B)
{'x': 1}
```
After:
```python
>>> A = make_config(x=1)
>>> B = make_config(x=[1, 2], bases=(A,))  # must be a mutable value to trigger the bug
>>> instantiate(B)
{'x': [1, 2]}
```
We achieve this by detecting the particular conditions for which this bug occurs:
- The user is not using a newer version of `omegaconf`, where this bug is fixed
- and.. the config sets a mutable default value via default-value factory
- and.. the config inherits from one or more parent dataclasses
- and.. the parent also provides a field of the same name
- and.. the …

Patch upstream omegaconf issue #830

---

src/hydra_zen/structured_configs/_implementations.py
tests/test_signature_parsing.py

This PR changes the behavior of `builds` when `populate_full_signature=True` and one or more base-classes are specified for inheritance. **Notes that this a compatibility-breaking change**. Although the old behavior was likely not what one wanted/expected.
Previously, fields specified by the parent class would take priority over those that would be auto-populated:
```python
from hydra_zen import builds, make_config
def f(x=1):
pass
Parent = make_config(x="hi")
```
**Before**
```python
>>> builds(f, populate_full_signature=True, builds_bases=(Parent,))  # x comes from parent
Builds_f(x='hi', _target_='__main__.f')
>>> builds(f, x=1, builds_bases=(Parent,))() 
Builds_f(x=1, _target_='__main__.f')
```
However, this behavior is unintuitive, as `populate_full_signature=True` should behave …

Change behavior of pop-full-sig to take priority over inherited fields

---

src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

Closes #173 
Broadens our type-annotations for mutable containers (dicts, sets, lists, deques) to avoid the risk of users hitting false-positives in their code. ~On the downside, we can no longer provide precise feedback about whether, e.g., a list has OK contents for Hydra via our annotations.~ (EDIT: See [comment](https://github.com/mit-ll-responsible-ai/hydra-zen/pull/175#issuecomment-986170971)).  At runtime we still provide accurate checking.

Loosen type annotations to avoid false-positives on mutable generic containers

---

src/hydra_zen/structured_configs/_implementations.py
tests/test_signature_parsing.py
tests/test_value_conversion.py

In the release of `v0.4.0`, I failed to document the compatibility-breaking change in how we support enums. Furthermore, it came to my attention that the change could introduce substantial, cumbersome changes in how a user configures and launches an app that involve enums. Lastly, the change disabled Hydra's ability to validate enum-types.
Thus this PR reverts the enum-specific changes introduced in #163 . I.e. we once again defer to the default omegaconf/Hydra support for enums.

Revert compat-breaking enum change introduced in v0.4.0

---

.github/workflows/nightly.yml
.github/workflows/tox_run.yml
src/hydra_zen/_launch.py
src/hydra_zen/structured_configs/_implementations.py

[This bug](https://github.com/microsoft/pyright/issues/2746) in pyright 1.1.198 has been fixed. Minimum version of pyright on our CI is now 1.1.199 (the latest release as of posting this).
The newest version of pyright located some incomplete type annotations, which this PR also fixes.

Fix inaccurate type info and unpin pyright

---

src/hydra_zen/structured_configs/_implementations.py

This PR only makes improvements to hydra-zen's internal code structure; there are no changes in behavior.
The type-sanitization process that occurs in `builds` now occurs in a single location, alongside where value-sanitization. This makes it easier to understand, and possibly change, this behavior.

Code cleanup: centralized type-sanitization

---

src/hydra_zen/structured_configs/_implementations.py
tests/test_signature_parsing.py

`builds` performs type-widening when users specify targeted configs as default values. This prevents common friction with Hydra's validation system; see https://github.com/mit-ll-responsible-ai/hydra-zen/pull/84 
However, this type-widening behavior is too aggressive: A targeted config type should not be broadened to `Any` since this is a valid type that can be leveraged by Hydra's runtime validation. Thus this PR fixes this, so that dataclass-types are retained and thus can be leveraged by Hydra for validation.
**Before**:
```python
from hydra_zen import builds, instantiate
BuildsInt = builds(int)
def f_with_dataclass_annotation(x: BuildsInt = BuildsInt()):
return x
```
```python
>>> bad_value = builds(str)()  # not an instance of `BuildsInt`
>>> …
```

Improve type-widening and add tests

---

src/hydra_zen/_compatibility.py
src/hydra_zen/_hydra_overloads.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/structured_configs/_value_conversion.py
src/hydra_zen/typing/__init__.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_compatibility/test_hydra_supports_partial.py
tests/test_compatibility/test_omegaconf_830.py
tests/test_config_value_validation.py
tests/test_hydra_behaviors.py
tests/test_protocols.py
tests/test_roundtrips.py
tests/test_utils.py
tests/test_value_conversion.py

Closes #183 (I am tracking https://github.com/omry/omegaconf/issues/846 and https://github.com/facebookresearch/hydra/issues/1112 to begin testing new features in nightly builds)
Closes #182 
This PR:
- Reorganizes some of our internal utilities and tests to make it easier for us to adaptively support new features provided by OmegaConf/Hydra.
- Version-specific flags are now set in `hydra_zen._compatibility`. E.g. `HYDRA_SUPPORTS_PARTIAL` indicates whether a user's local install of Hydra is recent enough to support the `_partial_` API.
- The primitive types supported by Hydra and hydra-zen, respectively, are now specified in `hydra_zen._compatibility`. This will enable us to accommodate #181 and future changes to Hydra's supported primitives.
- A shortcoming here is that the types in …

Improves internal code organization; adds future support for `_partial_`

---

src/hydra_zen/structured_configs/_implementations.py
tests/test_roundtrips.py
tests/test_signature_parsing.py
tests/test_third_party/test_against_torch.py
tests/test_value_conversion.py

This PR provides two significant improvements to the ability of `hydra_zen.builds` to parse a target's signature:
Previously, `builds(<target>, ...)` did not look at `target.__new__` for annotations, even if that is where the signature was derived from. This has been fixed. Consider the following:
```python
from hydra_zen import make_custom_builds_fn
import inspect
builds = make_custom_builds_fn(populate_full_signature=True)
class A:
def __new__(cls, a: int, b: bool):
...
```
```python
>>> inspect.signature(A)
<Signature (a: int, b: bool)>
```
Before:
```python
>>> inspect.signature(builds(A))
<Signature (a: Any, b: Any) -> None>
```
After:
```python
>>> inspect.signature(builds(A))
<Signature (a: int, b: bool) -> None>
```
There is [a bug in `inspect.signature` for Python < …

Improve signature parsing in `builds`

---

src/hydra_zen/_compatibility.py

We implemented future support for `_partial_` in Hydra's instantiate API, but we should not permit this to be toggled "on" on the user's end until we can actually test our support in our CI.

Don't enable support for _partial_ until we can begin running CI against it

---

src/hydra_zen/_compatibility.py
src/hydra_zen/structured_configs/_implementations.py
tests/test_utils.py

`_get_version` was breaking on dev-versions. E.g. `0.2.4dev1`

Internal fixes

---

docs/source/api_reference.rst
src/hydra_zen/_compatibility.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_protocols.py
tests/test_value_conversion.py

Partially addresses #197 
Now users can directly specify a "partial'd" object -- i.e. an object produced by `functools.partial(...)` -- directly as a configured value in `make_config` and `builds`. 
Consider the following.
```python
from hydra_zen import make_config, instantiate
from functools import partial
def f(x, y): 
return (x, y)
```
Before
```python
>>> make_config(v=partial(f, x=1))
HydraZenUnsupportedPrimitiveError: ...
```
After:
```python
>>> Conf = make_config(v=partial(f, x=1))
>>> instantiate(Conf)
>>> {'v': functools.partial(<function f at 0x0000015924B6A700>, x=1)}
```
Under the hood, `make_config` and `builds` will identify `partial`-type configured values and "unpack" them, so that we can use `builds(..., zen_partial=True)` to create a valid targeted config that …

Support partial'd object as configured value

---

src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

Before:
```python
builds(1)  # OK to static type-checkers
```
After:
```python
builds(1)  # marked as invalid by static type-checkers
```

improve type annotation for builds -- target must be callable

---

.github/workflows/nightly.yml
tests/annotations/declarations.py

See https://github.com/microsoft/pyright/releases/tag/1.1.211
Before:
```python
x: Literal["int"] = reveal_type(len[1,2])
```
After:
```python
reveal_type(len[1,2], expected_string="int")
```

pyright 1.1.211 behavior change

---

docs/source/how_to/pytorch_lightning.rst

`optim` was imported, but also used as a variable in `__init__`

Avoid shadowed variable name in PL example

---

.github/workflows/nightly.yml
.github/workflows/tox_run.yml
pyrightconfig.json
src/hydra_zen/funcs.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
tests/annotations/declarations.py

We can now check that pyright sees particular invocations of our code as "erroneous". E.g., we can now verify that a line like
```python
builds(1)
```
will be marked as an error by static type checkers. This is achieved by configuring pyright to raise whenever `# type: ignore` is used unnecessarily. Thus we can write
```python
builds(1)  # type: ignore
```
that pyright then runs without issue thus indicates that it indeed did suppress an error on that line. 
We also unpin pyright, specifying 1.1.213 as the new minimum version.

Add contrapositive pyright tests

---

docs/source/conf.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

Our protocols: `Builds`, `PartialBuilds`, and `Just` failed to mark their class variables with [`ClassVar`](https://docs.python.org/3/library/typing.html#typing.ClassVar). This has been fixed. This also removes `HasPartialTarget` which wasn't used in any meaningful way.
Before:
```python
builds(int)._target_  # pyright `error:` Builds does not define _target_ as a ClassVar
```
After:
```python
builds(int)._target_  # OK, reveals type str
```
Additionally, some of the annotations for these attributes were made to be more precise. E.g. `PartialBuilds._zen_partial` can only be `True` in order to carry the downstream behavior of `PartialBuilds` as opposed to `Builds`. Thus its annotation has been revised from `bool` to `Literal[True]`.

Improves our protocols

---

tests/test_signature_parsing.py

This test ensures that the type-widening that we introduced in #207 is actually necessary - it will fail if OmegaConf/Hydra changes its validation to accommodate this case, and thus it will indicate that the widening can be removed.

Test that type-widening for interp field is necessary

---

.github/workflows/nightly.yml
.github/workflows/tox_run.yml
README.md
pyrightconfig.json
src/hydra_zen/_hydra_overloads.py
src/hydra_zen/_launch.py
src/hydra_zen/funcs.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/third_party/beartype.py
src/hydra_zen/third_party/pydantic.py
src/hydra_zen/typing/_builds_overloads.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

pyright provides a utility for [verifying type completeness for "py.typed" packages](https://github.com/microsoft/pyright/blob/92b4028cd5fd483efcf3f1cdb8597b2d4edd8866/docs/typed-libraries.md#verifying-type-completeness). 
This PR revamps hydra-zen's annotations so that its type completeness score is 100%. Our CI will now check that we maintain this score.
[dcb8061](https://github.com/mit-ll-responsible-ai/hydra-zen/pull/226/commits/dcb806150a7cc7e832d0e21cd06e3d46511a3b0d) confirms that our CI correctly fails when hydra-zen does not reach 100% type completeness [CI](https://github.com/mit-ll-responsible-ai/hydra-zen/runs/5227421315?check_suite_focus=true):
```
Type completeness score: 65.8%  ( 😢 )
```
[da713b6](https://github.com/mit-ll-responsible-ai/hydra-zen/pull/226/commits/da713b66f0 …

Achieve type completeness (pyright-strict)

---

src/hydra_zen/_compatibility.py
tests/test_utils.py

This PR improves our internal version-checking utilities for making Hydra/omegaconf compatibility checks.

Require patch info in version comparisons

---

.github/workflows/tox_run.yml
setup.cfg
src/hydra_zen/_compatibility.py
src/hydra_zen/structured_configs/_implementations.py
tests/test_protocols.py
tests/test_zen_wrappers.py

This PR enables compatibility with Hydra's new support for `_partial_` in its instantiate API. For Hydra > 1.1.1, "partial'd" configs will no longer need to leverage `zen_processing` (assuming no other zen-features are utilized):
Before:
```python
>>> from hydra_zen import builds, to_yaml
>>> Conf = builds(int, zen_partial=True)
>>> print(to_yaml(Conf))
_target_: hydra_zen.funcs.zen_processing
_zen_target: builtins.int
_zen_partial: true
```
After (assuming `hydra-core>1.1.1` is installed):
```python
>>> Conf = builds(int, zen_partial=True)
>>> print(to_yaml(Conf))
_target_: builtins.int
_partial_: true
```
This PR also adds CI tests against 1.1.2dev, so that we test against both 1.1.2dev and 1.2.0dev in our suite.

Enable `_partial_` for Hydra > 1.1.1

---

src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/typing/_builds_overloads.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

This PR introduces `BuildsWithSig` as an internal protocol; it may be exposed via the public `hydra_zen.typing` API in the future.
We improve the annotation for `builds(<target>, populate_full_signature=True)` so that the resulting type, `BuildsWithSig`, is a subclass of the `Builds` protocol.
#224 modified the annotation overloads for `builds` so that `builds(<target>, populate_full_signature=True)` returned the type `Callable[P, Builds[Type[R]]]`, where `P` and `R` are the signature and type of `<target>`, respectively. 
While this enables auto-completion / signature inference to static tooling, the issue is that the return type is a generic callable and not a subclass of `Builds`. This can lead to some glaring false-positives to type-checkers; e.g.
where the type-checker raises:
``` …
```

Adds BuildsWithSig protocol

---

docs/source/changes.rst
docs/source/conf.py
src/hydra_zen/typing/__init__.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_compatibility/test_hydra_supports_partial.py
tests/test_protocols.py

In light of #230 this PR changes implementation of `PartialBuilds` to reflect that `builds(<target>, zen_partial=True)` can implement either the `_partial_` protocol or the `_zen_partial` protocol. Accordingly, `hydra_zen.typing` now exposes two protocols: `HydraPartialBuilds` and `ZenPartialBuilds`, and `PartialBuilds` is their union.
Any libraries that leverage `PartialBuilds` in their type annotations will likely not see any breaking changes in their static analysis. However, code that used `PartialBuilds` to perform runtime checking will need to update their code:
e.g., from
```python
>>> from hydra_zen.typing import PartialBuilds
>>> Conf = builds(int, zen_partial=True)
>>> isinstance(Conf, PartialBuilds)
True
```
to
```python
>>> from hydra_zen.typing import HydraPartialBuilds, …
```

Revise implementation of `PartialBuilds`

---

src/hydra_zen/_hydra_overloads.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

Closes #241 
This PR improves compatibility of `hydra_zen.instantiate` with mypy:
```python
from dataclasses import dataclass
from hydra_zen import instantiate
@dataclass
class OptimizerConf:
_target_: str
_partial_: bool = True
optimizer_conf = OptimizerConf(_target_="torch.optim.SGD")
reveal_type(instantiate(optimizer_conf))
```
mypy's support for dataclasses is limited, and there does not appear to be a way to spell dataclass-based protocols for mypy. Thus this new overload introduces a false-negative: `instantiate` can accept any object with a `_target_: str` attribute. Given that the above use case is a common use case, it is worth tolerating this relatively obscure false-negative (how many things have `_target_: str` attributes?) in favor of avoiding a very common false-positive in …

Improve instantiate overload

---

src/hydra_zen/structured_configs/_make_custom_builds.py
tests/annotations/declarations.py

Overloads now handle bool-type inputs; previously only `Literal[True/False])` were handled properly. 
Added much more complete type tests. Confirmed manually that `mypy` parses the overloads correctly too

Add missing overloads for `make_custom_builds_fn`

---

.github/workflows/nightly.yml
.github/workflows/tox_run.yml
src/hydra_zen/_hydra_overloads.py
src/hydra_zen/structured_configs/__init__.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_just.py
src/hydra_zen/structured_configs/_value_conversion.py
src/hydra_zen/typing/_implementations.py
tests/__init__.py
tests/annotations/declarations.py
tests/test_just.py
tests/test_roundtrips.py
tests/test_third_party/test_against_torch.py
tests/test_validation.py

Closes #201 
hydra-zen can [automatically construct targeted configs for values of certain types](https://mit-ll-responsible-ai.github.io/hydra-zen/api_reference.html#additional-types-supported-via-hydra-zen).
E.g.
```python
>>> from hydra_zen import make_config, to_yaml
>>> Conf = make_config(value=2.0 + 3.0j)
>>> print(to_yaml(Conf))
value:
real: 2.0
imag: 3.0
_target_: builtins.complex
```
Prior to this PR, this functionality could only be leveraged indirectly, via `builds` and `make_config`. Now, `just` can directly convert values to corresponding structured config instances. E.g.
```python
>>> from hydra_zen import just
>>> just(1+2j)
ConfigComplex(real=1.0, imag=2.0, _target_='builtins.complex')
```
`just` operates recursively within sequences and mappings.
```python
>>> just({'a': …
```

Extend the functionality of `just` to work with all Hydra/hydra-zen supported types

---

docs/source/api_reference.rst
docs/source/changes.rst
src/hydra_zen/_hydra_overloads.py
src/hydra_zen/structured_configs/_just.py
tests/test_hydra_overloads.py
tests/test_just.py

Previously, creating/saving the yaml representation for [values of types supported specifically by hydra-zen](https://mit-ll-responsible-ai.github.io/hydra-zen/api_reference.html#additional-types-supported-via-hydra-zen) required a user to manually apply `just` to those values to convert them to structured configs:
Before:
```python
>>> from functools import partial
>>> from hydra_zen import just, to_yaml
>>> print(just(to_yaml({"a": [1+2j, partial(int, 3)]})))  # requires call to `just`
a:
- real: 1.0
imag: 2.0
_target_: builtins.complex
- _target_: builtins.int
_partial_: true
_args_:
- 3
```
Now, `to_yaml` and `save_yaml` will automatically apply `just` when appropriate.
**After**
```python
>>> from hydra_zen import just, to_yaml
>>> print(to_yaml({"a": [1+2j, partial(int, 3)]}))  # no …
```

`to_yaml` and `save_yaml` now reflect hydra-zen's extended type support

---

src/hydra_zen/_hydra_overloads.py
tests/annotations/declarations.py

Fixes:
```python
x: Any
instantiate(x)  # type: Path
```
(Didn't realize that `Any` "tight binds" like that...)

fix instantiate overloads for Any

---

src/hydra_zen/_compatibility.py
src/hydra_zen/structured_configs/_utils.py
tests/test_third_party/test_type_validators.py
tests/test_utils.py

omegaconf 2.2.0 adds supports for nested container types: https://github.com/omry/omegaconf/pull/890
Previously, hydra-zen applied automatic type-widening for nested container types:
```python
import inspect
def f(x: List[Dict[int, List[str]]]): pass
Conf = builds(f, populate_full_signature=True)
inspect.signature(Conf)  # <Signature (x: List[Any]) -> None>
```
Now, if `omegaconf >= 2.2.0` is installed, `builds` will permit nested container types.
```python
Conf = builds(f, populate_full_signature=True)
inspect.signature(Conf)  # <Signature (x: List[Dict[int, List[str]]]) -> None>
```
Type-widening still applies within nested containers:
```python
def f(x: List[List[Type[int]]): pass  # Type[int] is not supported
Conf = builds(f, populate_full_signature=True)
inspect.signature(Conf)  # …
```

Enable nested container types for omegaconf 2.2.0

---

docs/source/api_reference.rst
src/hydra_zen/_compatibility.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_compatibility/test_primitive_support.py
tests/test_just.py
tests/test_utils.py
tests/test_value_conversion.py

Closes #181 
`bytes` has had [specialized support from hydra-zen](https://mit-ll-responsible-ai.github.io/hydra-zen/api_reference.html#additional-types-supported-via-hydra-zen). OmegaConf 2.2.0 adds native support for `bytes` (https://github.com/omry/omegaconf/pull/845).
Now if OmegaConf 2.2.0 or higher is installed, hydra-zen will defer to OmegaConf's native support for bytes.
OmegaConf < 2.2.0 installed:
```python
import inspect
from hydra_zen import builds, to_yaml
def f(x: bytes): ...
Conf = builds(f, x=b'123')
inspect.signature(Conf)  # <Signature (x: Any = Builds_bytes(_target_='builtins.bytes', _args_=((49, 50, 51),))) -> None>
print(to_yaml(Conf))
```
```
_target_: __main__.f
x:
_target_: builtins.bytes
_args_:
- - 49
- 50
- 51
```
OmegaConf >= 2.2.0 installed:
```python
import …
```

Enable native support for `bytes` for omegaconf 2.2.0

---

src/hydra_zen/structured_configs/_make_custom_builds.py
tests/test_make_custom_builds_fn.py

Exposing `builds_bases` via `make_custom_builds` makes our annotation overloads substantially more complicated. This is a rarely-used (maybe never!) feature. Thus this PR deprecates the `builds_bases` argument in `make_custom_builds`. It will be removed in hydra-zen v0.8.0. Users will need to specify `builds_bases` on a per-config basis.

Deprecates `builds_bases` via `make_custom_builds`

---

src/hydra_zen/structured_configs/_utils.py
tests/test_utils.py

#261 enabled annotations for nested containers for omegaconf > 2.2.0. It incorrectly permitted nested tuples. This PR fixes that.

Fix overly-permissive annotation: nested tuples

---

setup.cfg
src/hydra_zen/_launch.py
tests/test_launch/test_implementations.py
tests/test_make_custom_builds_fn.py

This PR does two things:
- Adds flag to convert a `dataclass` input to a `DictConfig`.  This is a fix and response to the cloudpickle [issue](https://github.com/cloudpipe/cloudpickle/issues/386)
- Refactors `launch` to comform with Hydra's Compose API.  Currently we cannot use `compose` as it does not support `muliturn`, but these changes make it easy to update if `compose` eventually supports `multirun`. 
@rsokl I added cloudpickle to some of the test requirements.  I'm not sure how to test without it.

Updates to `launch`

---

docs/source/changes.rst
src/hydra_zen/_launch.py
tests/conftest.py
tests/test_defaults_list.py
tests/test_launch/test_callbacks.py
tests/test_launch/test_implementations.py
tests/test_launch/test_logging.py
tests/test_launch/test_validation.py

This mirrors functionality that will be exposed by `hydra.run` and `hydra.initialize` starting with Hydra 1.2.0:
- If the `version_base` parameter is not specified, Hydra 1.x will use defaults compatible with version 1.1. Also in this case, a warning is issued to indicate an explicit version_base is preferred.
- If the `version_base` parameter is `None`, then the defaults are chosen for the current minor Hydra version. For example for Hydra 1.2, then would imply `config_path=None` and `hydra.job.chdir=False`.
- If the `version_base` parameter is an explicit version string like "1.1", then the defaults appropriate to that version are used.
Our tests will specify `version_base` in accordance with the local version of Hydra, unless otherwise appropriate, via a pytest fixture.

Adds `version_base` to `launch`

---

docs/source/api_reference.rst
docs/source/changes.rst
setup.cfg
src/hydra_zen/_compatibility.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_just.py
src/hydra_zen/structured_configs/_make_config.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/structured_configs/_value_conversion.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_compatibility/test_primitive_support.py
tests/test_just.py
tests/test_utils.py

- Defer to Hydra support for `pathlib.Path` when appropriate
- Also bypasses hydra-zen fix for https://github.com/omry/omegaconf/issues/830 when appropriate.
- Fixes failing tests caused by release of hydra 1.2.0

Defer to Hydra support for `pathlib.Path`

---

setup.cfg
setup.py
src/hydra_zen/structured_configs/_utils.py
tests/test_third_party/test_type_validators.py
tests/test_utils.py

Prior to this, the presence of `ParamSpecArgs` or `ParamSpecKwargs` in a signature being parsed by `builds` would cause an unhashable type error.
This PR fixes this bug and adds support for extracting information from `Annotated` and `NewType`, and adds support for extrapolating from variadic tuples (e.g. `Tuple[int, *Ts]`) 
Test cases are also added for `Protocol` and `TypeVar`
```python
>>> sanitized_type(Annotated[int, range(10)])
Any
>>> sanitized_type(NewType("H", str))
Any
>>> sanitized_type(Tuple[*Ts])
Tuple[Any]
>>> sanitized_type(P.args)  # error
>>> sanitized_type(P.kwargs)  # error
```
```python
>>> sanitized_type(Annotated[int, range(10)])
int
>>> sanitized_type(NewType("H", str))
str
>>> sanitized_type(Tuple[*Ts])
Tuple[Any, ...]
>>> sanitized_type(P.args)
Any
>>> …
```

Improved signature parsing: support for Annotated, Paramspec, NewType, TypeVarTuple

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_make_config.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_defaults_list.py

The following default lists are valid but were not permitted by hydra-zen:
- `[{"a": None}]`  (discovered in #284 )
- `[DictConfig({"a": "b"})]`
- `[make_config(a="b")]`
- `[{"a": ListConfig(["b"])]`
This PR broadens the validation performed by hydra-zen, plus updates the type-annotations and docs for `hydra_defaults`. 
The spec for Hydra's Defaults List can be found [here](https://hydra.cc/docs/next/advanced/defaults_list/)

Broaden overly-restrictive hydra_defaults validation

---

.github/workflows/tox_run.yml
setup.cfg

omegaconf 2.2.3 and 2.2.2 diverge in support for some annotations -- this CI job ensures that we don't silently regress for omegaconf 2.2.2

add CI job for omegaconf 2.2.2

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
tests/test_value_conversion.py

Closes #295 
```python 
from typing import Any
from hydra_zen import builds, instantiate
from dataclasses import field, dataclass
@dataclass
class A:
x: Any = field(default_factory=lambda : [1, 2, 3])
```
**Before:**
```python
>>> builds(A, populate_full_signature=True)
HydraZenUnsupportedPrimitiveError: Building: A ..
The configured value <factory>, for field `x`, is not supported by Hydra -- serializing or instantiating this config would ultimately result in an error.
Consider using `hydra_zen.builds(<class 'dataclasses._HAS_DEFAULT_FACTORY_CLASS'>, ...)` create a config for this particular value.
```
**After**
```python
>>> Conf = builds(A, populate_full_signature=True)
>>> instantiate(Conf)
A(x=[1, 2, 3])
```

Add support for builds(Dataclass, populate_full_signature=True) when dataclass has default factory fields

---

docs/source/api_reference.rst
docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
tests/test_third_party/test_using_pydantic.py

Given:
```python
from pydantic.dataclasses import dataclass as pyd_dataclass
from pydantic import Field
@pyd_dataclass
class A:
x: int = Field(default=2, gt=0, lt=3)
```
**Before**:
```python
>>> from hydra_zen import builds
>>> builds(A, populate_full_signature=True)  # presence of `pydantic.Field` causes error
---------------------------------------------------------------------------
HydraZenUnsupportedPrimitiveError: Building: A ..
The configured value default=2 gt=0 lt=3 extra={}, for field `x`, is not supported by Hydra -- serializing or instantiating this config would ultimately result in an error.
Consider using `hydra_zen.builds(<class 'pydantic.fields.FieldInfo'>, ...)` create a config for this particular value.
```
**After**
```python
>>> from hydra_zen import builds, just, …
```

Adds auto-config support for `pydantic.Field`

---

.github/workflows/nightly.yml
.github/workflows/tox_run.yml
docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
tests/annotations/mypy_checks.py

- blocker for `just`: https://github.com/python/mypy/issues/13623
- blocker for `@hydrated_dataclass`:  https://github.com/python/mypy/issues/12840

Add mypy tests for basic use cases of public functions

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_make_custom_builds.py
tests/annotations/declarations.py
tests/test_make_custom_builds_fn.py

Fulfills deprecation set in 0.7.0: https://github.com/mit-ll-responsible-ai/hydra-zen/pull/263

Remove `builds_bases` option from `make_custom_builds_fn`

---

.github/workflows/tox_run.yml
docs/source/how_to/pytorch_lightning.rst
pyproject.toml
tests/test_docs_typecheck.py

Ensure pyright docs scan has 3rd party libraries installed so that pyright can validate against their interfaces as well

Separate out pyright docs scan job

---

.flake8
.github/workflows/tox_run.yml
.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml
src/hydra_zen/typing/_implementations.py

CI will now run: black, isort, flake8. The job will fail if black or isort would have made a formatting change. The job will fail if flake8 sees an issue.

add actions job to enforce formatting

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_just.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

Our pyright tests for Partial weren't tight enough to catch some issues with the current protocol.
The following failed to type check prior to 7d93063:
```python
def f() -> int:
...
def g(x: str) -> bool:
...
x: Partial[int] = partial(f)
y: Partial[bool] = partial(g, x="a")
```

Improve `Partial` protocol

---

.github/workflows/tox_run.yml
docs/source/changes.rst
src/hydra_zen/wrapper/_implementations.py
tests/__init__.py
tests/annotations/declarations.py
tests/annotations/mypy_checks.py

A subclassed `ZenStore` will now return the correct type -- the subclass -- when self-partialing. This works for both pyright and mypy.
E.g.
```python
from hydra_zen.wrapper import ZenStore
class MyStore(ZenStore):
...
store = MyStore()
optim_store = store(group="optim")
reveal_type(optim_store)
```

Use Self annotation in store self-partialing

---

src/hydra_zen/structured_configs/_utils.py
tests/test_utils.py

Given:
```python
from dataclasses import dataclass, InitVar
from inspect import signature
from hydra_zen import builds
@dataclass
class A:
x: InitVar[int]
Conf = builds(A, populate_full_signature=True)
```
Before:
```python
>>> signature(Conf)
<Signature (x: Any) -> None>
```
After:
```python
>>> signature(Conf)
<Signature (x: int) -> None>
```

Add type conversion support for `InitVar`

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
tests/test_launch/test_merge_compat.py

Closes #449 I.e. configs produced by `just` can now be merged into configs by Hydra.
This is a backwards-compatibility breaking change, but it should be of negligible negative impact.

`just` no longer produces frozen dataclass instances

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
tests/test_signature_parsing.py

https://github.com/python/cpython/issues/105080 updates the behavior of `inspect.signature` to walk through a class' mro in search of its signature, rather than just defer to the most recent definition of `__new__`.
This PR updates the signature inspection logic of `builds` to match this new behavior of `inspect.signature` across all versions of Python. I.e. this effectively serves as a backport.
Here is an example that exhibits this change in behavior:
```python
class A:
def __new__(cls, a: int):
return object.__new__(cls)
class B(A):
def __init__(self, b: float):  ...
class C(B):
...
```
Before:
The signature of `A.__new__` was preferred over that of `B.__init__` even though the latter is closer to `C` in the inheritance hierarchy.
```python
>>> import inspect
>>> from hydra_zen import …
```

Update `builds` signature inspection for python 3.11.4 change

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_make_custom_builds.py

A patch for v0.10:  This patch circumvents an upstream bug in pyright, which was causing pyright 1.1.305+ to report the return type of :func:`hydra_zen.make_custom_builds_fn` as "Unknown".

v0.10.2: Fix pyright's failure to handle  `make_custom_builds_fn`

---

CONTRIBUTING.md

It looks like the name of the docstrings test (the one where one should place the examples) has changed its name.

Update test link in CONTRIBUTING.md

---

docs/source/index.rst
pyproject.toml
tests/pyright_utils.py
tests/test_docs_typecheck.py

Instead of:
```python
scan_results = [pyright_analyze(obj) for obj in stuff]
```
Do:
```python
scan_results = pyright_analyze(*stuff)
```
and it'll be *way* faster. Only pay for pyright startup once and pyright knows how to parallelize.
Our pytest run on pyright docs-scan goes from 81s to 20s!

Change `pyright_analyze` to scan multiple files in parallel

---

src/hydra_zen/structured_configs/_type_guards.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py

Compatible with pyright 1.1.331. There are still pyright errors, but these are false positives.

Fix typing errors

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_make_custom_builds.py
tests/custom_strategies.py
tests/test_custom_strategies.py
tests/test_zen_exclude.py

This PR adds the ability to exclude parameters - either by name or by pattern (i.e. `callable[[name], bool]`) - from `builds` when `populate_full_signature=True`.
```python
from hydra_zen import builds
def f(x=1, y=2, _z=3): ...
builds(f, populate_full_signature=True, zen_exclude=['y'])  # exclude `y` from config
builds(f, populate_full_signature=True, zen_exclude=lambda x: x.startwith("_")  # exclude any param starting with "_"
```
or
```python
from hydra_zen import make_custom_builds_fn
builds = make_custom_builds_fn(populate_full_signature=True, zen_exclude=lambda x: x.startwith("_"))
```
Note that this does **not** enable one to exclude inherited parameters.
I have wanted to implement `zen_exclude` for a while, but doing so would make our typing-overloads for …

Add `zen_exclude` option to `builds` and `make_custom_builds_fn`

---

src/hydra_zen/wrapper/_implementations.py
tests/test_BuildsFn.py

This makes it easy to have ZenStore's default auto-config capabilities leverage a specialized config-creation functions.
E.g., suppose `CustomBuilds` is a subclass of `BuildsFn`, which has added auto-config support for `MyType`. Then we can create a config whose auto-config behavior leverages these added capabilities.
```python
from hydra_zen.wrapper import default_to_config
from hydra_zen import ZenStore
from functools import partial
store = ZenStore("my store")(
to_config=partial(default_to_config, BuildsFn=CustomBuilds)
)
```
```python
>>> from hydra_zen import instantiate
>>> store(SomeType, x=1, y=SomeType(2), name='boo')
>>> instantiate(store[None, "boo"])
SomeType(1, SomeType(2, None))
```

Make `default_to_config` customizable with `BuildsFn`

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
tests/test_BuildsFn.py
tests/test_staticmethod_support.py

hydra-zen's config creation functions now have special logic for determining the import-path of a static method. E.g.
Given:
```python
class A:
@staticmethod
def f(): return "woo"
```
Before:
```python
>>> from hydra_zen import builds, instantiate
>>> instantiate(builds(A.f))
--------------------------------------------
InstantiationException: Error locating target '__main__.f', set env var HYDRA_FULL_ERROR=1 to see chained exception.
```
After:
```python
>>> from hydra_zen import builds, just, instantiate
>>> instantiate(builds(A.f))                 
woo
>>> instantiate(just(A.f))
<function __main__.A.f()>
```
It is not possible to distinguish a staticmethod that has already been bound to a class versus a function. That being said, we can inspect the `__qualname__` of a function to see …

Add automatic config-creation support for staticmethods

---

docs/source/changes.rst
docs/source/generated/hydra_zen.ZenStore.rst
src/hydra_zen/wrapper/_implementations.py
tests/test_dataclass_semantics.py
tests/test_store.py

Adds the following methods to `ZenStore`
- `copy`
- `copy_with_mapped_groups`
- `delete_entry` (or, `__delitem__`)
- `enqueue_all`
- `update` (or, `__ior__`)
- `merge` (or, `__or__`)
- `__len__`

Add features to `ZenStore`

---

docs/source/changes.rst
pyproject.toml
src/hydra_zen/wrapper/_implementations.py
tests/test_zen.py
tests/test_zen_context_isolation.py

This PR adds the ability to run a zen-wrapped function in an isolated copy of [`contextvars.Context`](https://docs.python.org/3/library/contextvars.html) by specifying `zen(func, run_in_context=True)`.  I.e. changes made to any `contextvars.ContextVar` will be isolated to that call of the wrapped function.
This permits some powerful patterns where you can make information (e.g., about your run's config) globally available to any function called within the wrapped function - via `contextvars.ContextVar` - without having to worry about state bleeding outside of runs.
Check this out
```python
from contextvars import ContextVar
from dataclasses import dataclass
from hydra_zen import zen
@dataclass
class Config:
x: int
experiment_name: str
config_var: ContextVar[Config] = ContextVar("config") …
```

Add `zen(..., run_in_context: bool)`

---

.github/workflows/tox_run.yml
pyproject.toml
src/hydra_zen/structured_configs/_implementations.py
tests/conftest.py
tests/test_third_party/test_using_pydantic.py
tests/test_third_party/test_using_v1_pydantic.py

- Closes https://github.com/mit-ll-responsible-ai/hydra-zen/issues/585
- Adds smoke test for pydantic v2 to make sure merely importing pydantic v2 w/ hydra-zen doesn't break things

Add rudimentary support for pydantic.BaseModel and for pydantic 2.0

---

src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/wrapper/_implementations.py
tests/test_BuildsFn.py
tests/test_store.py
tests/test_third_party/test_using_v1_pydantic.py

Fixes bug introduced by #562 where users could no longer specify `populate_full_signature` in the config store's kw
Also make calls to pydantic safer across versions

fix store autoconfig issue

---

docs/source/changes.rst
src/hydra_zen/structured_configs/_implementations.py
tests/test_zen_exclude.py

E.g.
```python
>>> from hydra_zen import builds, to_yaml
>>> def pyaml(x):
...     # for pretty printing configs
...     print(to_yaml(x))
>>> def bar(x: bool, y: str = 'foo'): return x, y
>>> Conf2 = builds(bar, populate_full_signature=True, zen_exclude=[-1]) # exclude last param
>>> pyaml(Conf2)
_target_: __main__.bar
x: ???
```

Support parameter-indices in zen-exclude

---

src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_manual_target.py

E.g., here we use `foo` as a target and lift the parameters from its signature, but then specify the `_target_` to actually instantiate `bar`:
```python
from hydra_zen import builds, instantiate, to_yaml
def pyaml(x):
print(to_yaml(x))
def foo(x=1, y=2):
...
def bar(**kw):
return f"bar({kw=})"
Conf = builds(
foo,
populate_full_signature=True,
zen_dataclass={"target": "__main__.bar"},
)
pyaml(Conf)
instantiate(Conf)
```
```
_target_: __main__.bar
x: 1
'y': 2
"bar(kw={'x': 1, 'y': 2})"
```

Adds the ability to manually override `_target_` in `builds`

---

docs/source/api_reference.rst
docs/source/changes.rst
docs/source/generated/hydra_zen.kwargs_of.rst
src/hydra_zen/__init__.py
src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/structured_configs/_utils.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_kwargs_of.py
tests/test_zen.py

(Very excited about this one!)
This PR adds a new config-creation function:
```python
>>> from inspect import signature
>>> from hydra_zen import kwargs_of, instantiate
>>> Config = kwargs_of(lambda x, y: None)
>>> signature(Config)
<Signature (x:Any, y: Any) -> None>
>>> config = Config(x=1, y=2)
>>> config
kwargs_of_lambda(x=1, y=2)
>>> instantiate(config)
{'x': 1, 'y': 2}
```
Excluding the first parameter from the target's signature:
```python
>>> Config = kwargs_of(lambda *, x, y: None, zen_exclude=[0])
>>> signature(Config)
<Signature (y: Any) -> None>
>>> instantiate(Config(y=88))
{'y': 88}
```
Like `builds` and `just`, `kwargs_of` is a classmethod of `BuildsFn` and thus is customizable accordingly.
This function is powerful because it decouples a config from the target, meaning …

Adds `hydra_zen.kwargs_fn`

---

src/hydra_zen/structured_configs/_implementations.py
tests/annotations/declarations.py

E.g.
```python
def bar(x: int, y: str, z: bool):
...
kwargs_of(bar, zen_exclude=(0,))  # pyright sees: type[BuildsWithSig[type[Dict[str, Any]], (y: str, z: bool)]]
```

Improve `kwargs_of` annotations

---

.github/workflows/pypi_publish.yml
src/hydra_zen/structured_configs/_type_guards.py

Patch coverage and bump actions

---

src/hydra_zen/structured_configs/_implementations.py
src/hydra_zen/typing/_implementations.py
tests/annotations/declarations.py
tests/test_BuildsFn.py

partials are supported in `CustomConfigType` but we missed this case, leading to a false positive in type checking.

Update `CustomConfigType` to support `Partial[T]`

---

.github/workflows/tox_run.yml
pyproject.toml

https://github.com/python/importlib_resources/issues/298 is causing issues in Hydra for Python 3.8. It is most appropriate for Hydra to handle the pinning here as it is the one introducing the dependency. So we are just doing a CI-level pin so that we can keep testing vs Python 3.8.

CI-only: Pin importlib-resources<6.2

---

src/hydra_zen/structured_configs/_implementations.py
tests/test_staticmethod_support.py

Closes #705
Given:
```python
from hydra_zen import builds, instantiate
class Outer:
class Inner:
pass
cfg = builds(Outer.Inner)
```
Before:
```python
>>> instantiate(cfg)
InstantiationException: Error locating target '__main__.Inner'
```
After:
```python
>>> instantiate(cfg)
Outer.Inner()
```

Update _get_obj_path to support ClassA.ClassB

---

src/hydra_zen/structured_configs/_implementations.py

I assume `f` is supposed to be `bar` in this example?

Fixed builds auto-populating example doc

---

src/hydra_zen/wrapper/_implementations.py

While working on https://github.com/python/mypy/pull/16715 I've noticed that `_StoreCallSig` uses class form, while having `__kw` field. This field will be mangled. This is not something typing users want. See https://github.com/python/cpython/issues/129567

Refactor `_StoreCallSig` to inline form

---

src/hydra_zen/_hydra_overloads.py
src/hydra_zen/funcs.py
src/hydra_zen/structured_configs/_implementations.py
tests/test_instantiate.py
tests/test_third_party/test_using_all_pydantic.py
tests/test_utils.py

Closes https://github.com/mit-ll-responsible-ai/hydra-zen/issues/717 by deferring the wrapping process for partialed outputs. Now a special class -- `partial_with_wrapper` -- is used so that the resulting partial'd object exposes the expected, unwrapped, `.func` object, and is pickle-compatible by storing the wrapper
```python
import pickle
import hydra_zen
import torch.optim
from hydra_zen.third_party.pydantic import pydantic_parser
AdamConfig = hydra_zen.builds(
torch.optim.Adam,
populate_full_signature=True,
zen_partial=True,
zen_exclude=["params"],
zen_dataclass={
"cls_name": "AdamConfig",
"module": "hydra_zen_issue_debug",
"frozen": True,
},
zen_wrappers=[pydantic_parser],  # comment this out to make it work below.
)
obj = AdamConfig(lr=3e-4)
fn = hydra_zen.instantiate(obj) …
```

Improve `_target_wrapper_` behavior when doing partial instantiation
